"""Create users states table

Revision ID: e9d5ca60bc3c
Revises: 2d95cf0deb87
Create Date: 2025-12-16 09:12:59.425820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9d5ca60bc3c"
down_revision: Union[str, Sequence[str], None] = "2d95cf0deb87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_states",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_messages", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
            name=op.f("fk_user_states_chat_id_chats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_states")),
        sa.UniqueConstraint(
            "chat_id", "telegram_user_id", name="uq_user_state_chat_user"
        ),
    )
    op.create_index(
        op.f("ix_user_states_chat_id"), "user_states", ["chat_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_states_telegram_user_id"),
        "user_states",
        ["telegram_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_states_telegram_user_id"), table_name="user_states")
    op.drop_index(op.f("ix_user_states_chat_id"), table_name="user_states")
    op.drop_table("user_states")
    # ### end Alembic commands ###
