"""Create chats admins table

Revision ID: 2d95cf0deb87
Revises: d47a225ef863
Create Date: 2025-12-16 09:11:05.083697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d95cf0deb87"
down_revision: Union[str, Sequence[str], None] = "d47a225ef863"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_admins",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
            name=op.f("fk_chat_admins_chat_id_chats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_admins")),
        sa.UniqueConstraint(
            "chat_id", "telegram_user_id", name="uq_chat_admin_chat_user"
        ),
    )
    op.create_index(
        op.f("ix_chat_admins_chat_id"), "chat_admins", ["chat_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_admins_telegram_user_id"),
        "chat_admins",
        ["telegram_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_admins_telegram_user_id"), table_name="chat_admins")
    op.drop_index(op.f("ix_chat_admins_chat_id"), table_name="chat_admins")
    op.drop_table("chat_admins")
    # ### end Alembic commands ###
